module.exports = {
    TEMPERATURE: 'R1',
    TEMPERATURE_MIN: 'R1_MIN',
    TEMPERATURE_MAX: 'R1_MAX',
    WATER_LEVEL: 'S1',
    HORIZONTAL_VELOCITY: 'U1',
    HORIZONTAL_VELOCITY_MIN: 'U1_MIN',
    HORIZONTAL_VELOCITY_MAX: 'U1_MAX',
    VERTICAL_VELOCITY: 'V1',
    VERTICAL_VELOCITY_MIN: 'V1_MIN',
    VERTICAL_VELOCITY_MAX: 'V1_MAX',
    TIME: 'time',
    DEPTH: 'ZK',
    LATITUDE: 'YCOR',
    LONGITUDE: 'XCOR',
    VELOCITY: 'velocity'
};
