module.exports = {
    TEMPERATURE: 'R1',
    TEMPERATURE_MIN: 'R1_MIN',
    TEMPERATURE_MAX: 'R1_MAX',
    WATER_LEVEL: 'S1',
    HORIZONTAL_VELOCITY: 'U1',
    VERTICAL_VELOCITY: 'V1',
    VELOCITY_MIN: 'UV_MIN',
    VELOCITY_MAX: 'UV_MAX',
    TIME: 'time',
    DEPTH: 'ZK',
    LATITUDE: 'YCOR',
    LONGITUDE: 'XCOR',
    VELOCITY: 'velocity'
};
